import React, {useState} from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import First from '../components/First';
import Intro from '../components/Intro';
import Works from '../components/Works';
import Footer from '../components/Footer';
import Loading from '../components/Loading'

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [loading, setLoading] = useState(true);
  return (
    <>
    {
      loading? 
      <Loading loading={loading} setLoading={setLoading}/>
      :
      <>
      <Head>
        <title>Sherif Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[#000000e1] text-white">
        <Intro />
        <First />
        <Works />
        <Footer />
      </main>
      </>
    }
      
    </>
  );
}
