import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import First from '../components/First';
import Intro from '../components/Intro';
import Works from '../components/Works';
import Footer from '../components/Footer';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Sherif Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[#000000e1]">
        <Intro />
        <First />
        <Works />
        <Footer />
      </main>
    </>
  );
}
